import xml.etree.ElementTree as ET
import argparse
import logging
import subprocess
_log = logging.getLogger(__name__)


def add_element(tree, name, text):
    """
    Add elements to an xml object
    :param tree: xml object to append to
    :param name: name attribute of the item
    :param text: text of the item to add
    :return: tree with appended item
    """
    new = ET.Element("att")
    new.attrib["name"] = name
    new.text = text
    tree.append(new)


def update_doc(glider, mission, kind):
    """
    Edit the xml generated by GenerateDatasetsXml.sh
    :param glider: glider number
    :param mission: mission number
    :param kind: nrt or complete
    :return: 
    """
    document_loc = f"/home/usrerddap/erddap/xml_edit/xml/OG_{kind}_{glider}_M{mission}.xml"
    tree = ET.parse(document_loc)
    root = tree.getroot()
    # Update dataset name
    ds_name = f"OG_{kind}_{glider}_M{mission}"
    root.attrib["datasetID"] = ds_name
    for child in root:
        # fix for addAttributes
        if child.tag == "addAttributes":
            add_attrs = child
            edit_add_attrs_og(add_attrs)


    # fix indentation and write xml
    ET.indent(tree, '  ')
    out = f"/home/usrerddap/erddap/content/parts/{ds_name}.xml"
    tree.write(out, encoding="utf-8", xml_declaration=True)
    _log.info(f"Recombining datasets.xml")
    subprocess.check_call(['/usr/bin/bash', "/home/usrerddap/erddap/xml_edit/make_datasets.sh"])




def edit_add_attrs_og(adds):
    for child in adds:
        if child.attrib["name"] == "cdm_trajectory_variables":
            adds.remove(child)
        if child.attrib["name"] == "subsetVariables":
            adds.remove(child)

    add_element(adds, "cdm_data_type", "Trajectory")
    add_element(adds, "cdm_trajectory_variables", "TRAJECTORY")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Add an OG1 dataset to ERDDAP')
    parser.add_argument('glider', type=str, help='glider , e.g. SEA070')
    parser.add_argument('mission', type=int, help='Mission number, e.g. 23')
    parser.add_argument('kind', type=str, help='Kind of dataset, must be nrt or delayed')
    args = parser.parse_args()
    if args.kind not in ['nrt', 'delayed']:
        raise ValueError('kind must be nrt or delayed')
    logf = f'/data/log/OG1_{args.kind}.log'
    logging.basicConfig(filename=logf,
                        filemode='a',
                        format='%(asctime)s %(levelname)-8s %(message)s',
                        level=logging.INFO,
                        datefmt='%Y-%m-%d %H:%M:%S')
    _log.info(f"Start add OG1 dataset {args.glider} M{args.mission} to xml")
    update_doc(args.glider, args.mission, args.kind)
    _log.info(f"Complete add OG1 dataset {args.glider} M{args.mission} to xml")
